function spm_NCA
% NCA Toolbox wrapper to call NCA functions
% ______________________________________________________________________
%
% Christian Gaser
% Structural Brain Mapping Group (https://neuro-jena.github.io)
% Departments of Neurology and Psychiatry
% Jena University Hospital
% ______________________________________________________________________

SPMid = spm('FnBanner',mfilename);
[Finter,Fgraph] = spm('FnUIsetup','neuroNCA 1.0');
%url = fullfile(fileparts(mfilename('fullpath')),'html','tfce.html');
%spm_help('!Disp',url,'',Fgraph,'Threshold-Free Cluster Enhancement Toolbox');

fig = spm_figure('GetWin','Interactive');
h0  = uimenu(fig,...
  'Label',  'neuroNCA',...
  'Separator',  'on',...
  'Tag',    'NCA',...
  'HandleVisibility','on');
h1  = uimenu(h0,...
  'Label',  'Estimate',...
  'Separator',  'off',...
  'Tag',    'Estimate NCA statistic',...
  'CallBack','spm_jobman(''interactive'','''',''spm.tools.NCA_estimate'');',...
  'HandleVisibility','on');